### ISSUE TITLE
Differences among main_moco_in, main_moco_out, main_moco_suploss

### ISSUE THREAD

**Issue by Chunngai** [zhangyifei01/MoCo-v2-SupContrast#1]
Hello. What are the differences among `main_moco_in`, `main_moco_out`, `main_moco_suploss`?

**Comment by pierowu** [comment]
> Hello. What are the differences among `main_moco_in`, `main_moco_out`, `main_moco_suploss`?

Hi! I have the same question. Have you figured out the differences now?
